server:
  port: 12000
spring:
  application:
    name: 'gateway-server'
  cloud:
    gateway:
      routes: #有多个配置的时候，就需要用  -
        - id: customer-Server #自定义的id唯一性 即可
          uri: lb://customer-server #   访问的目标服务器的地址（或者在eureka上面注册的名字）
          predicates: #如果请求满足这里 断言 的东西，才会发到服务器那里。
#            - Path=/** #任意路径都可以进行访问
            - Path=/customer/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
#            - Path=/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                #fallbackUri这个参数必须以  forward:/ 开头
                #然后 后面加上 相应的链接  （但这个东西是需要gateway模块自己去实现的
                fallbackUri: forward:/fallback #降级之后，只能传递给某个链接（这个链接来做降级操作。）

        - id: business-Server #自定义的id唯一性 即可
          uri: lb://business-server #   访问的目标服务器的地址（或者在eureka上面注册的名字）
          predicates: #如果请求满足这里 断言 的东西，才会发到服务器那里。
            #            - Path=/** #任意路径都可以进行访问
            - Path=/business/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          #            - Path=/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                #fallbackUri这个参数必须以  forward:/ 开头
                #然后 后面加上 相应的链接  （但这个东西是需要gateway模块自己去实现的
                fallbackUri: forward:/fallback #降级之后，只能传递给某个链接（这个链接来做降级操作。）

        - id: delivery-address-Server #自定义的id唯一性 即可
          uri: lb://delivery-address-server #   访问的目标服务器的地址（或者在eureka上面注册的名字）
          predicates: #如果请求满足这里 断言 的东西，才会发到服务器那里。
            #            - Path=/** #任意路径都可以进行访问
            - Path=/address/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          #            - Path=/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                #fallbackUri这个参数必须以  forward:/ 开头
                #然后 后面加上 相应的链接  （但这个东西是需要gateway模块自己去实现的
                fallbackUri: forward:/fallback #降级之后，只能传递给某个链接（这个链接来做降级操作。）

        - id: food-Server #自定义的id唯一性 即可
          uri: lb://food-server #   访问的目标服务器的地址（或者在eureka上面注册的名字）
          predicates: #如果请求满足这里 断言 的东西，才会发到服务器那里。
            #            - Path=/** #任意路径都可以进行访问
            - Path=/food/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          #            - Path=/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                #fallbackUri这个参数必须以  forward:/ 开头
                #然后 后面加上 相应的链接  （但这个东西是需要gateway模块自己去实现的
                fallbackUri: forward:/fallback #降级之后，只能传递给某个链接（这个链接来做降级操作。）

        - id: order-detail-Server #自定义的id唯一性 即可
          uri: lb://order-detail-server #   访问的目标服务器的地址（或者在eureka上面注册的名字）
          predicates: #如果请求满足这里 断言 的东西，才会发到服务器那里。
            #            - Path=/** #任意路径都可以进行访问
            - Path=/orderDetail/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          #            - Path=/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                #fallbackUri这个参数必须以  forward:/ 开头
                #然后 后面加上 相应的链接  （但这个东西是需要gateway模块自己去实现的
                fallbackUri: forward:/fallback #降级之后，只能传递给某个链接（这个链接来做降级操作。）

        - id: order-table-Server #自定义的id唯一性 即可
          uri: lb://order-table-server #   访问的目标服务器的地址（或者在eureka上面注册的名字）
          predicates: #如果请求满足这里 断言 的东西，才会发到服务器那里。
            #            - Path=/** #任意路径都可以进行访问
            - Path=/orderTable/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          #            - Path=/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                #fallbackUri这个参数必须以  forward:/ 开头
                #然后 后面加上 相应的链接  （但这个东西是需要gateway模块自己去实现的
                fallbackUri: forward:/fallback #降级之后，只能传递给某个链接（这个链接来做降级操作。）

      globalcors: #是在gateway下面,需要分清楚
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "GET, HEAD, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "*"
eureka: #这里都是发给服务注册中心看的
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5 #5秒时间，互动一次，sayHi
    lease-expiration-duration-in-seconds: 15 #
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 30
        minimum-number-of-calls: 1
        sliding-window-type: time_based
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 2s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions: #记录异常
          - java.lang.Exception
    instances:
      backendA:
        base-config: default
