server:
  port: 12000
spring:
  application:
    name: 'gateway-server'
  cloud:
    gateway:
      routes: #有多个配置的时候，就需要用  -
        - id: consumerServer #自定义的id唯一性 即可
          #这里的lb 意味着 loadbalance缩写。因为eureka上面可能有多个同名服务，所以需要顺便启动loadbalance服务才可以
          uri: lb://customer-server #   访问的目标服务器的地址（或者在eureka上面注册的名字）
          predicates: #如果请求满足这里 断言 的东西，才会发到服务器那里。
#            - Path=/** #任意路径都可以进行访问
            - Path=/customer/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
#            - Path=/**  #两个 ** 表示这里的东西是任意的。  会把这里的path转发给uri
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                #fallbackUri这个参数必须以  forward:/ 开头
                #然后 后面加上 相应的链接  （但这个东西是需要gateway模块自己去实现的
                fallbackUri: forward:/fallback #降级之后，只能传递给某个链接（这个链接来做降级操作。）

        - id: providerServer
          uri: lb://customer-server
          predicates:
            - Path=/user/**

      globalcors: #是在gateway下面,需要分清楚
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "GET, HEAD, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "*"
eureka: #这里都是发给服务注册中心看的
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5 #5秒时间，互动一次，sayHi
    lease-expiration-duration-in-seconds: 15 #
  client: #写这一段就可以注册到eureka上面了
    service-url: #因为eureka是集群，所以  ，（逗号）  连接
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 30
        minimum-number-of-calls: 1
        sliding-window-type: time_based
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true #自动 开到半开
        wait-duration-in-open-state: 2s
        permitted-number-of-calls-in-half-open-state: 3 #半开允许数量3
        record-exceptions: #记录异常
          - java.lang.Exception
    instances:
      backendA:
        base-config: default





